module.exports = ["Britney Spears", "Jay Z", "Eminem", "Destiny's Child", "Green Day",
 "Micheal Jackson", "Spice Girls", "Radio Head", "Backstreet Boys", "Red Hot Chili Peppers",
  "Prince", "Whitney Houston", "Christina Aguilera", "Snoop Dogg", "Justin Timberlake",
   "Janet Jackson", "Weezer", "U2", "Smashing Pumpkins", "Oasis", "Kenny Chesney", "Metallica",
    "Alice In Chains", "Foo Fighters", "Jennifer Lopez", "Lady Gaga", "Kesha", "Gwen Stefani",
     "Nicole Scherzinger", "Paris Hilton", "Katy Perry", "Lindsay Lohan", "The Pussycat Dolls",
      "Kanye West", "Drake", "2Pac", "The Notorious B.I.G.", "Lil Wayne", "J. Cole", "T.I.",
       "Timbaland", "Kendrick Lamar", "50 Cent", "D12", "JAY Z", "Dr. Dre", "Ken Kaniff", "Obie Trice",
        "Bad Meets Evil", "Ludacris", "Kelly Rowland", "TLC", "Christina Milian", "Ciara", "Amerie",
         "Brandy", "Mýa", "Aaliyah", "Beyoncé", "Alicia Keys", "The Offspring", "blink-182", "Sum 41",
          "Good Charlotte", "Simple Plan", "Thirty Seconds To Mars", "Bowling For Soup", "Rise Against",
           "Michael Jackson", "Jackie Jackson", "Jermaine Jackson", "The Jackson 5", "Adam Levine",
            "Stevie Wonder", "Melanie C", "Geri Halliwell", "Atomic Kitten", "Girls Aloud", "Victoria Beckham",
             "Emma Bunton", "Mel B", "Sugababes", "*NSYNC", "IN-Q", "Kele Fleming",
              "Frank Garrett", "Frank Silvera", "Jørgen Leth", "Celestial Navigations", "Frank Pettingell",
               "Hawke", "Micah", "New Kids On The Block", "Hanson", "Nick Carter", "S Club 7", "O-Town",
                "Five", "Westlife", "Savage Garden", "Nirvana", "Incubus", "Audioslave", "Lenny Kravitz",
                 "Jane's Addiction", "Pearl Jam", "Rage Against The Machine", "Romeo Santos", "Aventura",
                 "Toby Love", "Leslie Grace", "Carlos y Alejandra", "Wisin", "Ivy Queen", "Monchy & Alexandra",
                 "Chino & Nacho", "Tito El Bambino", "Mariah Carey", "Tina Turner", "Toni Braxton",
                 "Vanessa Williams", "Céline Dion", "Lionel Richie", "Diana Ross", "P!nk", "Jessica Simpson",
                 "Kelly Clarkson", "Nelly Furtado", "Xzibit", "Ice Cube", "Warren G", "Nate Dogg", "N.W.A.",
                 "The Game", "Rihanna", "Usher", "Fergie", "Robin Thicke", "The Black Eyed Peas", "Mary J. Blige",
                 "En Vogue", "Faith Evans", "Ashanti", "Cake", "The Presidents Of The United States Of America",
                 "Harvey Danger", "Marcy Playground", "Third Eye Blind", "Everclear", "Phantom Planet", "Lit",
                 "Wheatus", "Eve 6", "R.E.M.", "Queen", "David Bowie", "The Cranberries", "Aerosmith", "Peter Gabriel",
                  "Sting", "Bruce Springsteen", "The Police", "Silverchair", "Blind Melon", "Stone Temple Pilots",
                   "Local H", "Bush", "Soundgarden", "The Verve", "Blur", "Noel Gallagher", "Travis",
                   "Noel Gallagher's High Flying Birds", "The Stone Roses", "Beady Eye", "Supergrass", "Stereophonics",
                    "Manic Street Preachers", "Tim McGraw", "Brad Paisley", "Blake Shelton", "Toby Keith",
                    "Dierks Bentley", "Keith Urban", "Gary Allan", "Billy Currington", "Rascal Flatts", "Jason Aldean",
                     "Megadeth", "Slayer", "Anthrax", "Pantera", "Testament", "Motörhead", "Machine Head", "Sepultura",
                      "Suicidal Tendencies", "Iron Maiden", "Temple Of The Dog", "Jerry Cantrell", "Mad Season",
                      "Candlebox", "Mother Love Bone", "Queens of the Stone Age", "The Smashing Pumpkins", "Dave Grohl",
                       "Taylor Hawkins & The Coattail Riders"];
