module.exports = ["Jay Z", "Eminem", "Destiny's Child", "Green Day",
 "Michael Jackson", "Radiohead", "Red Hot Chili Peppers",
  "Prince", "Whitney Houston", "Christina Aguilera", "Snoop Dogg", "Justin Timberlake",
   "Janet Jackson", "Weezer", "U2", "Smashing Pumpkins", "Oasis", "Kenny Chesney", "Metallica",
    "Alice In Chains", "Foo Fighters", "Lady Gaga", "Kesha", "Gwen Stefani",
     "Katy Perry", "The Pussycat Dolls",
      "Kanye West", "Drake", "2Pac", "The Notorious B.I.G.", "Lil Wayne",
       "Kendrick Lamar", "50 Cent", "JAY Z", "Dr. Dre",
        "Ludacris", "Rihanna", "Usher", "Fergie",
        "The Offspring", "blink-182", "Sum 41",
        "Good Charlotte", "Simple Plan", "Thirty Seconds To Mars", "Bowling For Soup", "Rise Against",
        "Nirvana", "Incubus", "Audioslave",
        "Pearl Jam", "Rage Against The Machine",
        "Third Eye Blind", "Everclear",
        "Blind Melon", "Stone Temple Pilots",
        "The Police", "The Jackson 5",
        "Harvey Danger", "Queen",
        "Queens of the Stone Age", "The Smashing Pumpkins", "Beyoncé",
        "Iron Maiden", "Brad Paisley", "The Black Eyed Peas", "Stevie Wonder",
        'the beatles', 'led zeplin', 'acdc', 'david bowie', 'bob dylan', 'ray charles', 'buckcherry',
'garbage', 'everlast', 'the lumineers', 'of monsters and men', 'mumphord and sons', 'five for fighting',
'asap rocky', 'drake', '2 chainz', 'kendrick lamar', 'lil wayne', 'train', 'g-eazy', 'hailee steinfeld',
'matt and kim', 'bon iver', 'explosions in the sky', 'big sean', 'kanye west', 'john legend', 'cage elephant',
'zedd', 'the killers', 'flo rida', 'florence and the machine', 'childish gambino', 'moby', 'the fray', 'tegan and sara',
'the heavy', 'david guetta', 'lynyrd skynyrd', 'ariana grande', 'mac miller', 'kansas', 'lake street dive', 'eazy-e',
'adele', 'band of horses', 'nappy roots', 'kid kudi', 'dmx', 'regina spektor', 'grits', 'tracy chapmen', 'jeff buckley',
'cash cash', 'busta rhymes', 'mgmt', 'shaggy', 'calvin harris', 'daughter', 'yaz', 'lukas graham', 'taylor swift',
'the weekend', 'tom odell', 'rick ross', 'echosmith', 'matchbox 20', 'dispatch', 'modest mouse', 'sia', 'lupe fiasco',
'aretha franklin', 'the verve', 'dave matthews band', 'counting crows', 'goo goo dolls', 'the doors', 'the smiths',
'my chemical romance', 'wale', 'avicii', '21 pilots', 'cold play', 'magic!', 'the neighbourhood', 'karmin', 'the shins', 'the pixies',
'the snow patrol', 'johnny cash', 'willie nelson', 'faith hill', 'the all american rejects', 'akon', 'young jeezy',
'ugk', 'outkast', 'ice cube', 'method man', 'redman', 'devin the dude', 'hieroglyphics', 'chamillionaire',
'kiss', 'tom petty', 'blondie', 'the village people', 'depeche mode', 'erasure', 'the steve miller band', 'fleetwood mac',
'simon and garfunkel', 'the grateful dead', 'the cardigans', 'jimi hendrix', 'lenny kravitz', 'pink floyd', 'arcade fire',
'relient k', 'franz ferdinand', 'death cab for cutie', 'wheatus', 'alicia keys', 'bruce springsteen', 'vertical horizon',
'kelly clarkson', 'carrie underwood', 'the gorillaz', 'cream', 'keak da sneak', 'chingy', 'fabolous', 'juvenile',
'immortal technique', 'maroon 5', 'elvis', 'the black keys', 'tool', 'the cheaters', 'fish',
'chevelle', 'talking heads', 'huey lewis and the news', 'rick astley', 'breaking benjamin', 'the monkeys',
'circa survive', 'anthony green', 'flume', 'hank williams jr.', 'journey', 'switchfoot', 'rush', 'pod', 'skillet',
'skrillex', 'the ramones', 'placebo', 'eric clapton', 'bone thugz n harmony', 'shakira', 'ozzy osbourne', 'morgan james'];
