module.exports = ["Britney Spears", "Jay Z", "Eminem", "Destiny's Child", "Green Day",
 "Micheal Jackson", "Spice Girls", "Radio Head", "Backstreet Boys", "Red Hot Chili Peppers",
  "Prince", "Whitney Houston", "Christina Aguilera", "Snoop Dogg", "Justin Timberlake",
   "Janet Jackson", "Weezer", "U2", "Smashing Pumpkins", "Oasis", "Kenny Chesney", "Metallica",
    "Alice In Chains", "Foo Fighters", "Jennifer Lopez", "Lady Gaga", "Kesha", "Gwen Stefani",
     "Katy Perry", "Lindsay Lohan", "The Pussycat Dolls",
      "Kanye West", "Drake", "2Pac", "The Notorious B.I.G.", "Lil Wayne",
       "Kendrick Lamar", "50 Cent", "JAY Z", "Dr. Dre",
        "Ludacris", "Rihanna", "Usher", "Fergie",
        "The Offspring", "blink-182", "Sum 41",
        "Good Charlotte", "Simple Plan", "Thirty Seconds To Mars", "Bowling For Soup", "Rise Against",
        "Michael Jackson",
        "Nirvana", "Incubus", "Audioslave",
        "Pearl Jam", "Rage Against The Machine",
        "Third Eye Blind", "Everclear",
        "Blind Melon", "Stone Temple Pilots",
        "The Police", "The Jackson 5",
        "Harvey Danger", "Hanson",
        "Queens of the Stone Age", "The Smashing Pumpkins", "Beyoncé",
        "Iron Maiden", "Brad Paisley", "The Black Eyed Peas", "Stevie Wonder"];
